# Generated by Django 4.0.6 on 2022-07-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=10)),
                ('product_details', models.TextField(max_length=225)),
                ('product_image', models.FileField(upload_to='static/image/item')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
