# Generated by Django 4.0.6 on 2022-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_buyproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproductmodel',
            name='status',
            field=models.CharField(default='delivered', max_length=10),
        ),
    ]
