# Generated by Django 4.0.6 on 2022-07-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='product_description',
            new_name='message',
        ),
    ]
